### PR TITLE
update yt_pattern and add unit test

### PR DESCRIPTION
**Pull request by ShanEllis**
edit to `yt_pattern` and added unit test

### CODE REVIEW

**Comment by muschellij2** [comment]
Can you see why it failed the checks:
https://github.com/muschellij2/didactr/pull/14/checks ?
John

**Comment by ShanEllis** [comment]
When I checked locally, got the following. Will look more closely later today, but figured I'd note this now.

```
❯ checking files in ‘vignettes’ ... WARNING
  Files in the 'vignettes' directory but no files in 'inst/doc':
    ‘New.png’, ‘Upload.png’, ‘checking_courses.Rmd’, ‘copy_url.png’,
      ‘creating_courses_from_scratch.Rmd’

❯ checking package vignettes in ‘inst/doc’ ... WARNING
  dir.exists(dir) is not TRUEdir.exists(dir) is not TRUE
  Package vignettes without corresponding single PDF/HTML:
     ‘checking_courses.Rmd’
     ‘creating_courses_from_scratch.Rmd’

❯ checking package dependencies ... NOTE
  Packages suggested but not available for checking: 'covr', 'pdftools'

0 errors ✔ | 2 warnings ✖ | 1 note ✖
Error: R CMD check found WARNINGs
Execution halted

Exited with status 1.
```

**Comment by ShanEllis** [comment]
So...I don't know for sure but in `checking_courses.Rmd`, it seems problematic that I don't have the following file to create the `auth_file` variable in that vignette for Travis purposes?

L38 causing issue: `auth_file = ..tests/testthat/googlesheets_token.rds`

It makes sense that you have that .gitignored....but I *believe* that's why Travis is failing for my most recent PR? Cant oauth for me?

It timed out while trying to create vignettes according to error message.

should I `eval = FALSE` that chunk? Or do you thinking something else could be going on?

**Comment by muschellij2** [comment]
That is a REAL token - if that was public - that would allow users to
access your/my drive.  Can't do that.

Best,
John

**Comment by ShanEllis** [comment]
Yea - I knew it was a real token - it was just getting hung up there....so
that's why I suggested eval=FALSE.

But, looks like you figured out the issue and it wasn't this anyway. Thanks!

**Pull request merged**
